#ifndef ULTRATERMINAL_NTVERP_H
#define ULTRATERMINAL_NTVERP_H

#include "term/version.h"

#define VER_PRODUCTVERSION IDV_PRODUCTVER
#define VER_PRODUCTVERSION_STR IDV_PRODUCTVERSION_STR
#define VER_PRODUCTNAME_STR IDV_PRODUCTNAME_STR
#define VER_FILEOS VOS__WINDOWS32

#if defined(WIN_DEBUG)
#define VER_FILEFLAGS (VS_FF_DEBUG | VS_FF_PRERELEASE)
#else
#define VER_FILEFLAGS (0L | VS_FF_PRERELEASE)
#endif

#endif
